CREATE TABLE places (
	id INT PRIMARY KEY,
	name VARCHAR(200) UNIQUE,
	address VARCHAR(500) UNIQUE NOT NULL,
	coordx VARCHAR(50) NOT NULL,
	coordy VARCHAR(50) NOT NULL 
);

CREATE TABLE tags (
	id INT PRIMARY KEY,
	name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE places_tags (
	id serial PRIMARY KEY,
    placesid INT NOT NULL,
    tagsid INT NOT NULL,
	FOREIGN KEY (placesid) REFERENCES places(id) ON UPDATE RESTRICT ON DELETE CASCADE,
	FOREIGN KEY (tagsid) REFERENCES tags(id)ON UPDATE RESTRICT ON DELETE CASCADE
);

CREATE TABLE users (
	id serial PRIMARY KEY,
	name VARCHAR(255) UNIQUE NOT NULL,
	pass VARCHAR(255) NOT NULL
);

CREATE TABLE history (
	id serial PRIMARY KEY,
	start timestamp NOT NULL,
	finish timestamp,
	usersid INT NOT NULL,
	placesid INT NOT NULL,
	FOREIGN KEY (usersid) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE CASCADE,
	FOREIGN KEY (placesid) REFERENCES places(id) ON UPDATE RESTRICT ON DELETE CASCADE
);
